# Uncomment the next line to define a global platform for your project
# platform :ios, '10.0'

target 'Handrating' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'TesseractOCRiOS', '~> 4.00' 
  # Pods for Handrating

  target 'HandratingTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
